databases:
  - name: task_manager_db
    databaseName: task_manager_ggfo
    user: grisha
    password: DhL0vYlO0yhzpxSg4HXIWWVmUXoza43s
    host: dpg-cl9knbto7jlc73ff5la0-a.frankfurt-postgres.render.com
    port: 5432
    ssl: true

services:
  - type: web
    name: task-manager
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    buildCommand: "./build.sh"
    startCommand: "gunicorn task_manager.wsgi:application"
