# Generated by Django 4.2.8 on 2023-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0005_tasksrelotionlabels_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', through='tasks.TasksRelotionLabels', to='labels.label', verbose_name='Labels'),
        ),
    ]
