name: run tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Create reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test and Report coverage
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          make test-coverage
          poetry run coverage lcov -o coverage/lcov.info
      - name: Sending Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.Coverage }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN" -t lcov
